import { PostWithExtras } from "@/lib/definitions";

export const postsWithExtras: PostWithExtras[] = [
  {
    id: "post_001",
    createdAt: new Date("2023-09-01"),
    updatedAt: new Date("2023-09-02"),
    caption: "Had a great time hiking!",
    fileUrl: "https://example.com/img/hiking.jpg",
    userId: "user_001",
    comments: [],
    likes: [],
    savedBy: [],
    user: {
      id: "user_001",
      name: "Alice Cooper",
      username: "alicecooper",
      bio: "Adventurer and traveler",
      website: "https://alicecooper.com",
      gender: "female",
      email: "alice@example.com",
      emailVerified: new Date("2023-02-01"),
      image: "https://example.com/profile/alice.jpg",
      createdAt: new Date("2022-07-01"),
      updatedAt: new Date("2023-09-01"),
    },
  },
  {
    id: "post_002",
    createdAt: new Date("2023-08-21"),
    updatedAt: new Date("2023-08-22"),
    caption: "Sunset at the beach",
    fileUrl: "https://example.com/img/sunset.jpg",
    userId: "user_002",
    comments: [],
    likes: [],
    savedBy: [],
    user: {
      id: "user_002",
      name: "Jane Doe",
      username: "janedoe",
      bio: "Love nature and photography",
      website: "https://janedoe.com",
      gender: "female",
      email: "janedoe@example.com",
      emailVerified: new Date("2023-01-01"),
      image: "https://example.com/profile/jane.jpg",
      createdAt: new Date("2022-09-01"),
      updatedAt: new Date("2023-09-01"),
    },
  },
  {
    id: "post_003",
    createdAt: new Date("2023-07-15"),
    updatedAt: new Date("2023-07-16"),
    caption: "Coding session",
    fileUrl: "https://example.com/img/coding.jpg",
    userId: "user_003",
    comments: [],
    likes: [],
    savedBy: [],
    user: {
      id: "user_003",
      name: "John Smith",
      username: "johnsmith",
      bio: "Tech enthusiast",
      website: "https://johnsmith.com",
      gender: "male",
      email: "johnsmith@example.com",
      emailVerified: new Date("2023-01-15"),
      image: "https://example.com/profile/john.jpg",
      createdAt: new Date("2022-08-15"),
      updatedAt: new Date("2023-08-15"),
    },
  },
];
